---
- name: run the main role
  hosts: all
  vars:
    file: true
    mysql: true
  roles:
    - {role: ansible-backup}

- name: install backup in mongoDB
  hosts: mongodb
  vars:
    mongodb: true
  roles:
    - {role: ansible-backup}
